const res = {
    msg: "ok",
    errorCode: 0,
    code: 200,
    data: [
        {
            id: 139,
            name: "公告发布",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:41:17",
            update_time: "2020-01-16 11:41:17",
            url: "notice",
            icon: "/assets/release.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 138,
            name: "删除5",
            type: 1,
            default: 1,
            state: 2,
            create_time: "2020-01-16 11:40:40",
            update_time: "2020-01-20 14:11:09",
            url: "notice",
            icon: "/assets/release.png",
            parent_id: 0,
            have: 2
        },
        {
            id: 137,
            name: "总订餐查询",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:40:23",
            update_time: "2020-01-16 11:40:23",
            url: "totalorder",
            icon: "/assets/search.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 136,
            name: "菜品管理(个人选菜)",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:40:09",
            update_time: "2020-01-16 11:40:09",
            url: "mealMenageSelf",
            icon: "/assets/manage.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 135,
            name: "菜品管理(菜谱查询)",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:39:54",
            update_time: "2020-01-17 10:02:11",
            url: "mealMenage",
            icon: "/assets/manage.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 134,
            name: "小卖部",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:37:20",
            update_time: "2020-01-16 11:37:20",
            url: "Store",
            icon: "/assets/canting.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 133,
            name: "设置",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:37:09",
            update_time: "2020-01-16 11:37:09",
            url: "setting",
            icon: "/assets/setting.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 132,
            name: "通知",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:36:53",
            update_time: "2020-01-16 11:36:53",
            url: "note",
            icon: "/assets/tongzhi.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 131,
            name: "微信充值",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:36:36",
            update_time: "2020-01-16 11:36:36",
            url: "recharge",
            icon: "/assets/chongzhi.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 130,
            name: "消费查询",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:36:21",
            update_time: "2020-01-16 11:36:21",
            url: "consume",
            icon: "/assets/xiaofei.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 129,
            name: "个人选菜",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:35:51",
            update_time: "2020-01-16 11:35:51",
            url: "selfdish",
            icon: "/assets/selfmenu.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 128,
            name: "菜谱查看",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:35:37",
            update_time: "2020-01-17 10:02:14",
            url: "menu",
            icon: "/assets/menu.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 127,
            name: "订单查询",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:35:10",
            update_time: "2020-01-16 11:35:10",
            url: "order",
            icon: "/assets/order.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 126,
            name: "删除4",
            type: 1,
            default: 1,
            state: 2,
            create_time: "2020-01-16 11:34:22",
            update_time: "2020-01-20 14:11:04",
            url: "menu",
            icon: "/assets/menu.png",
            parent_id: 0,
            have: 2
        },
        {
            id: 125,
            name: "删除3",
            type: 1,
            default: 1,
            state: 2,
            create_time: "2020-01-16 11:33:45",
            update_time: "2020-01-20 14:11:06",
            url: "selfdish",
            icon: "/assets/selfmenu.png",
            parent_id: 0,
            have: 2
        },
        {
            id: 124,
            name: "线上餐厅",
            type: 2,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:33:30",
            update_time: "2020-01-17 10:02:16",
            url: "orderingOnline",
            icon: "/assets/canting.png",
            parent_id: 0,
            have: 1
        },
        {
            id: 121,
            name: "小卖部设置",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:29:09",
            update_time: "2020-02-03 14:29:53",
            url: "CanteenSetting",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 123,
                    name: "微信端设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:29:29",
                    update_time: "2020-01-16 11:29:29",
                    url: "CanteenSetting-wechat",
                    icon: "",
                    parent_id: 121,
                    have: 1
                },
                {
                    id: 122,
                    name: "供应商管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:29:20",
                    update_time: "2020-01-16 11:29:20",
                    url: "CanteenSetting-supplier",
                    icon: "",
                    parent_id: 121,
                    have: 1
                }
            ]
        },
        {
            id: 117,
            name: "配置",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:28:26",
            update_time: "2020-01-16 11:28:26",
            url: "Configure",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 140,
                    name: "模块设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 14:55:11",
                    update_time: "2020-01-16 14:55:11",
                    url: "Configuring-modules-setting",
                    icon: "",
                    parent_id: 117,
                    have: 2
                },
                {
                    id: 120,
                    name: "模块管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:28:56",
                    update_time: "2020-01-16 11:28:56",
                    url: "Configuring-modules",
                    icon: "",
                    parent_id: 117,
                    have: 1
                },
                {
                    id: 119,
                    name: "企业管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:28:48",
                    update_time: "2020-01-16 11:28:48",
                    url: "Configuring-manage",
                    icon: "",
                    parent_id: 117,
                    have: 1
                },
                {
                    id: 118,
                    name: "企业明细",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:28:40",
                    update_time: "2020-01-16 11:28:40",
                    url: "Configuring-details",
                    icon: "",
                    parent_id: 117,
                    have: 1
                }
            ]
        },
        {
            id: 110,
            name: "设置",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:27:00",
            update_time: "2020-01-16 11:27:00",
            url: "Settings",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 116,
                    name: "删除33",
                    type: 1,
                    default: 1,
                    state: 2,
                    create_time: "2020-01-16 11:28:06",
                    update_time: "2020-02-03 14:30:01",
                    url: "Configure",
                    icon: "",
                    parent_id: 110,
                    have: 2
                },
                {
                    id: 115,
                    name: "密码设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:27:48",
                    update_time: "2020-01-16 11:27:48",
                    url: "Settings-password",
                    icon: "",
                    parent_id: 110,
                    have: 1
                },
                {
                    id: 114,
                    name: "角色设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:27:40",
                    update_time: "2020-01-16 11:27:40",
                    url: "Settings-role",
                    icon: "",
                    parent_id: 110,
                    have: 1
                },
                {
                    id: 113,
                    name: "消费策略设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:27:31",
                    update_time: "2020-01-16 11:27:31",
                    url: "Settings-consumption-strategy",
                    icon: "",
                    parent_id: 110,
                    have: 1
                },
                {
                    id: 112,
                    name: "部门人员设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:27:19",
                    update_time: "2020-01-16 11:27:19",
                    url: "Settings-department",
                    icon: "",
                    parent_id: 110,
                    have: 1
                },
                {
                    id: 111,
                    name: "补录管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:27:11",
                    update_time: "2020-01-16 11:27:11",
                    url: "Settings-supplement",
                    icon: "",
                    parent_id: 110,
                    have: 1
                }
            ]
        },
        {
            id: 105,
            name: "材料管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:26:12",
            update_time: "2020-01-16 11:26:12",
            url: "Material",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 109,
                    name: "材料价格明细",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:26:49",
                    update_time: "2020-01-16 11:26:49",
                    url: "Material-price-details",
                    icon: "",
                    parent_id: 105,
                    have: 1
                },
                {
                    id: 108,
                    name: "材料下单报表",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:26:40",
                    update_time: "2020-01-16 11:26:40",
                    url: "Material-Order",
                    icon: "",
                    parent_id: 105,
                    have: 1
                },
                {
                    id: 107,
                    name: "入库材料管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:26:32",
                    update_time: "2020-01-16 11:26:32",
                    url: "Material-storage",
                    icon: "",
                    parent_id: 105,
                    have: 1
                },
                {
                    id: 106,
                    name: "菜品材料明细",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:26:21",
                    update_time: "2020-01-16 11:26:21",
                    url: "Matertial-detail",
                    icon: "",
                    parent_id: 105,
                    have: 1
                }
            ]
        },
        {
            id: 96,
            name: "小卖部管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:24:27",
            update_time: "2020-01-16 11:24:27",
            url: "Canteen",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 104,
                    name: "进销统计报表(供)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:26:01",
                    update_time: "2020-01-16 11:26:01",
                    url: "Canteen-invocing-report-producer",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 103,
                    name: "订单明细查询(供)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:25:48",
                    update_time: "2020-01-16 11:25:48",
                    url: "Canteen-order-producer",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 102,
                    name: "消费订单汇总查询(供)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:25:35",
                    update_time: "2020-01-16 11:25:35",
                    url: "Canteen-statistics-producer",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 101,
                    name: "商品管理(供)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:25:23",
                    update_time: "2020-01-16 11:25:23",
                    url: "Canteen-manage",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 100,
                    name: "进销统计报表(管)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:25:12",
                    update_time: "2020-01-16 11:25:12",
                    url: "Canteen-invocing-report-manager",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 99,
                    name: "消费订单汇总查询(管)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:25:00",
                    update_time: "2020-01-16 11:25:00",
                    url: "Canteen-statistics-manager",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 98,
                    name: "订单明细查询(管)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:24:50",
                    update_time: "2020-01-16 11:24:50",
                    url: "Canteen-order-manager",
                    icon: "",
                    parent_id: 96,
                    have: 1
                },
                {
                    id: 97,
                    name: "商品查询(管)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:24:38",
                    update_time: "2020-01-16 11:24:38",
                    url: "Canteen-search",
                    icon: "",
                    parent_id: 96,
                    have: 1
                }
            ]
        },
        {
            id: 92,
            name: "菜品管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:23:43",
            update_time: "2020-01-16 11:23:43",
            url: "Cuisine",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 95,
                    name: "菜品管理(无选菜)",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:24:14",
                    update_time: "2020-01-16 11:24:14",
                    url: "Without-cuisine-manage",
                    icon: "",
                    parent_id: 92,
                    have: 1
                },
                {
                    id: 94,
                    name: "菜品管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:24:08",
                    update_time: "2020-01-16 11:24:08",
                    url: "Cuisine-manage",
                    icon: "",
                    parent_id: 92,
                    have: 1
                },
                {
                    id: 93,
                    name: "菜单设置",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:23:52",
                    update_time: "2020-01-16 11:23:52",
                    url: "Cuisine-settings",
                    icon: "",
                    parent_id: 92,
                    have: 1
                }
            ]
        },
        {
            id: 88,
            name: "充值管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:22:43",
            update_time: "2020-01-16 11:22:43",
            url: "Recharge",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 91,
                    name: "饭卡余额查询",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:23:33",
                    update_time: "2020-01-16 11:23:33",
                    url: "Recharge-card-balance",
                    icon: "",
                    parent_id: 88,
                    have: 1
                },
                {
                    id: 90,
                    name: "充值记录明细",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:23:24",
                    update_time: "2020-01-16 11:23:24",
                    url: "Recharge-record",
                    icon: "",
                    parent_id: 88,
                    have: 1
                },
                {
                    id: 89,
                    name: "现金充值",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:23:14",
                    update_time: "2020-01-16 11:23:14",
                    url: "Recharge-cash",
                    icon: "",
                    parent_id: 88,
                    have: 1
                }
            ]
        },
        {
            id: 87,
            name: "外卖管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:22:31",
            update_time: "2020-02-01 16:31:24",
            url: "TakeOut",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 141,
                    name: "外卖管理",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-02-01 17:00:37",
                    update_time: "2020-02-01 17:00:37",
                    url: "TakeOut-index",
                    icon: "",
                    parent_id: 87,
                    have: 1,
                }
            ]
        },
        {
            id: 84,
            name: "结算管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:22:02",
            update_time: "2020-01-16 11:22:02",
            url: "Settlement",
            icon: "",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 86,
                    name: "消费明细",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:22:21",
                    update_time: "2020-01-16 11:22:21",
                    url: "Settlement-details",
                    icon: "",
                    parent_id: 84,
                    have: 1
                },
                {
                    id: 85,
                    name: "消费统计",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:22:11",
                    update_time: "2020-02-03 14:30:20",
                    url: "Settlement-statistics",
                    icon: "",
                    parent_id: 84,
                    have: 1
                }
            ]
        },
        {
            id: 81,
            name: "订餐管理",
            type: 1,
            default: 1,
            state: 1,
            create_time: "2020-01-16 11:21:12",
            update_time: "2020-01-16 11:21:12",
            url: "Order",
            icon: "el-icon-document",
            parent_id: 0,
            have: 1,
            items: [
                {
                    id: 83,
                    name: "订餐明细",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:21:37",
                    update_time: "2020-01-16 11:21:37",
                    url: "Order-details",
                    icon: "",
                    parent_id: 81,
                    have: 1
                },
                {
                    id: 82,
                    name: "订餐统计",
                    type: 1,
                    default: 1,
                    state: 1,
                    create_time: "2020-01-16 11:21:23",
                    update_time: "2020-01-16 11:21:23",
                    url: "Order-statistics",
                    icon: "",
                    parent_id: 81,
                    have: 1
                }
            ]
        },
        {
            id: 80,
            name: "删除2",
            type: 1,
            default: 1,
            state: 2,
            create_time: "2020-01-16 11:08:30",
            update_time: "2020-01-20 14:11:21",
            url: "test",
            icon: "",
            parent_id: 0,
            have: 2
        }
    ]
};

export default res;